Json support
replikativ/datahike-server pull request #49
Opened 2022-07-01 14:18 UTC by yflim

Addresses #18.

##### Checklist
- [x] Implements an existing feature request. Make sure the feature request has been accepted for implementation before opening a PR.
- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Documentation added
- [ ] Architecture Decision Record added 
- [x] Formatting checked

2022-07-08 15:37 UTC, kordano commented
Let me know when this is finished and all conflicts are resolved.

2022-07-13 20:00 UTC, yflim commented
> Let me know when this is finished and all conflicts are resolved.
Done

2022-08-12 15:27 UTC, kordano requested changes
Very good job! Will be ready for merge once the small issue in the core is resolved.

2022-08-12 15:27 UTC, kordano commented on src/clj/datahike_server/core.clj
> -            [datahike-server.database]
both, `datahike-server.database` and `datahike-server.server` needs to be in here so the components can be mounted as you already mentioned in the tests.

2022-08-17 11:02 UTC, kordano approved these changes

2022-08-17 12:48 UTC, merged